name: "enhanced_you"
description: "Enhanced You is a mobile application that helps you to improve your life by providing you with a set of tools that will help you to achieve your goals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_app_name:
  name: "Enhanced You"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"



flutter:
  uses-material-design: true
