// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaOuBw8roGZEnESuIFGXnYqyaFQq2AYeQ',
    appId: '1:111890981065:web:cfd9e8d6f31e9ca2822d18',
    messagingSenderId: '111890981065',
    projectId: 'enhanced-you',
    authDomain: 'enhanced-you.firebaseapp.com',
    storageBucket: 'enhanced-you.appspot.com',
    measurementId: 'G-PLRKQ0HZ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI3mGsFxtk28e2xdEc-554gEFNP8aKdek',
    appId: '1:111890981065:android:1c8a054d2c06174b822d18',
    messagingSenderId: '111890981065',
    projectId: 'enhanced-you',
    storageBucket: 'enhanced-you.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFg_3YgtAz_5Zo3gk_LLxGYaHPOt8ctaI',
    appId: '1:111890981065:ios:8a5c092f55196cad822d18',
    messagingSenderId: '111890981065',
    projectId: 'enhanced-you',
    storageBucket: 'enhanced-you.appspot.com',
    androidClientId: '111890981065-oiik9gs02uq001jn4qvcpujus8753ddn.apps.googleusercontent.com',
    iosClientId: '111890981065-0tp0vbukbg99kg72j6f1444bn0k6t76q.apps.googleusercontent.com',
    iosBundleId: 'com.dakshbhatia.dayRule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFg_3YgtAz_5Zo3gk_LLxGYaHPOt8ctaI',
    appId: '1:111890981065:ios:cd4e70be5c6c79a6822d18',
    messagingSenderId: '111890981065',
    projectId: 'enhanced-you',
    storageBucket: 'enhanced-you.appspot.com',
    androidClientId: '111890981065-oiik9gs02uq001jn4qvcpujus8753ddn.apps.googleusercontent.com',
    iosClientId: '111890981065-sal7bukci6heedv7u2nm84h228gisha9.apps.googleusercontent.com',
    iosBundleId: 'com.dakshbhatia.dayRule.RunnerTests',
  );
}
